project:
  type: website
  output-dir: docs

website:
  title: "Rayyan Aamir"
  favicon: "images/logo_1.png"

  navbar:
    logo: "images/logo_1.png"

    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About

    right:
      - icon: github
        href: https://github.com/orchuk12
      - icon: linkedin
        href: https://www.linkedin.com/in/rayyan-shekhani/

  page-footer:
    left: |
      This website is an assignment based project for the unit<br>
      Communicating with Data (ETC5523) at Monash University,<br>
      Australia.
    border: true

    right: |
      Name: Rayyan Aamir<br>
      Student ID: 32065647<br>
      Email: raam0001@student.monash.edu

format:
  html:
    theme: solar
    css: styles.css



